import { BadGatewayException, Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

/**
 * Thin wrapper around GHTK's (Giao Hàng Tiết Kiệm) public "submit-order"
 * API — https://api.ghtk.vn/docs/submit-order/submit-order-express/ and
 * https://api.ghtk.vn/docs/submit-order/webhook/ (fetched directly from
 * GHTK's public docs, unlike the GHN client which was built without live
 * sandbox access — still re-verify against a real token/account before
 * relying on this in production, since docs can drift from the live API).
 *
 * Unlike GHN, GHTK's address fields are plain Vietnamese admin names
 * (province/district/ward as strings), not numeric codes — no address
 * resolver needed. The one real gap: GHTK still requires a "district" for
 * both pickup and delivery, a level our own `locations` module no longer
 * models (2025 reform: province → ward only) — see `GhtkService` for how
 * that's handled (pickup district is a per-branch config field; delivery
 * district is entered by the admin on the create-shipment form, since it
 * varies per order and we have no source to derive it from).
 *
 * **Mock mode**: when `GHTK_TOKEN` is unset, {@link createOrder} returns a
 * canned fake response instead of calling the real API, so the whole
 * create-shipment flow can be exercised with no credentials — set a real
 * `GHTK_TOKEN` to call the real API automatically, no other code change
 * needed. Mock responses are logged loudly and tracking codes are prefixed
 * `MOCK-GHTK-` so they can never be mistaken for a real shipment.
 */
export interface GhtkCreateOrderProduct {
  name: string;
  weight: number; // kg
  quantity?: number;
}

export interface GhtkCreateOrderPayload {
  order: {
    id: string; // our own order code, for reconciliation/idempotency on GHTK's side
    pick_name: string;
    pick_address: string;
    pick_province: string;
    pick_district: string;
    pick_ward?: string;
    pick_tel: string;
    name: string;
    address: string;
    province: string;
    district: string;
    ward: string;
    tel: string;
    pick_money?: number; // COD amount
    value?: number; // declared value for insurance/claims
    is_freeship?: 0 | 1;
    weight_option: 'kilogram';
    note?: string;
  };
  products: GhtkCreateOrderProduct[];
}

export interface GhtkCreateOrderResponse {
  success: boolean;
  order?: {
    label: string; // GHTK's tracking code
    tracking_id: number;
    fee: string;
    insurance_fee?: string;
    estimated_pick_time?: string;
    estimated_deliver_time?: string;
    status_id: number;
  };
  error?: { code?: string; ghtk_label?: string };
  message?: string;
}

@Injectable()
export class GhtkClient {
  private readonly logger = new Logger(GhtkClient.name);
  private readonly baseUrl: string;
  private readonly token: string;
  private readonly clientSource: string;

  constructor(config: ConfigService) {
    this.baseUrl = config.get<string>('ghtk.baseUrl') ?? '';
    this.token = config.get<string>('ghtk.token') ?? '';
    this.clientSource = config.get<string>('ghtk.clientSource') ?? '';
  }

  /** No `GHTK_TOKEN` configured — {@link createOrder} returns a mock response
   *  instead of hitting the real API. */
  get isMockMode(): boolean {
    return !this.token;
  }

  /** Fetch GHTK's printable label HTML for an existing shipment.
   *  Only called in real (non-mock) mode — mock labels are generated by
   *  `GhtkService.buildMockLabelHtml` so they can include full order data. */
  async getLabelHtml(trackingNo: string): Promise<string> {
    const res = await fetch(
      `${this.baseUrl}/services/label/v2?order_ids=${encodeURIComponent(trackingNo)}`,
      {
        headers: {
          Token: this.token,
          'X-Client-Source': this.clientSource,
        },
      },
    );
    if (!res.ok) {
      throw new BadGatewayException(
        `GHTK label API lỗi: ${res.statusText}`,
      );
    }
    return res.text();
  }

  async createOrder(
    payload: GhtkCreateOrderPayload,
  ): Promise<GhtkCreateOrderResponse> {
    if (this.isMockMode) {
      this.logger.warn(
        '[MOCK] GHTK_TOKEN chưa cấu hình — trả về dữ liệu giả cho tạo vận đơn. ' +
          'Đặt GHTK_TOKEN thật để gọi API thật, không cần sửa code.',
      );
      return {
        success: true,
        order: {
          label: `MOCK-GHTK-${Date.now()}`,
          tracking_id: Date.now(),
          fee: '18000',
          status_id: 1,
        },
      };
    }
    const res = await fetch(`${this.baseUrl}/services/shipment/order?ver=1.5`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Token: this.token,
        'X-Client-Source': this.clientSource,
      },
      body: JSON.stringify(payload),
    });
    const json = (await res
      .json()
      .catch(() => null)) as GhtkCreateOrderResponse | null;
    if (!res.ok || !json || json.success !== true || !json.order) {
      throw new BadGatewayException(
        `GHTK API lỗi: ${json?.message ?? json?.error?.code ?? res.statusText}`,
      );
    }
    return json;
  }
}
